taxiweb/config/routes.rb
Rails.application.routes.draw do
  get 'pages/historyservicies'

  resources :services
  
  get 'pages/pending_services'
  
  get 'services/:id/confirm', controller: :services, action: :confirm, as: :confirm_service
  get 'services/:id/favorite', controller: :services, action: :favorite, as: :favorite_service
  

  
  get 'pages/my_services/:id' , controller: :pages, action: :my_services, as: :pages_my_service

  get 'pages/estimate_cost'

  get 'pages/e'

  resources :profiles
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'pages#estimate_cost'

  get 'pages/about_us'

  get 'pages/faq'

  get 'pages/tos'

  get 'pages/contact_us'

end

taxiweb/app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessor :driverName, :userName
  belongs_to :user
  
    def driverName
      @driverName
    end
    
    def userName
      @userName
    end
    
    def dayFormat
      today = Time.new.in_time_zone('US/Pacific')
      date =''
      
      if self.day.strftime("%d") == today.strftime("%d")
        date = "Today " + self.day.strftime("%H:%M")
      else
        date = self.day.strftime("%d-%m  %H:%M")
      end
        date
    end
    
    def hasDriver
      self.driver!=nil
    end

  def hourservice
      time = self.day
      hour_aux = time.hour
      hour_to_s = ""
      min_to_s = ""
      am_pm = ""
      hour_to_s = time.hour.to_s
      min_to_s = time.min.to_s
      if hour_aux < 12
          am_pm = "am"
      else
          if hour_aux == 12
              hour_aux = 1
          else
              hour_aux = hour_aux - 12
          end
          am_pm = "pm"
      end
      if hour_aux < 10
          hour_to_s =  "0" + hour_aux.to_s
      end
      if time.min < 10
          min_to_s =  "0" + time.min.to_s
      end
      hour_to_s + ":" + min_to_s + " " + am_pm
  end
  
  def customerName
      myProfile = Profile.find_by(user_id: self.user_id)
      myProfile.full_name
  end
  
  def confirm
    self.confirmed = true
    self.save
  end
  
  def setFavorite
    self.favorite = !self.favorite 
    self.save
  end
  
  def nroConfirmation
      self.id.to_s +  self.day.strftime("%d%m")
  end
  
end

taxiweb/app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy, :confirm, :favorite]
  include GeneralHelper
  
  def something
    services_path
  end
  # GET /services
  # GET /services.json
  def index
    @services = Service.all.order(day: :desc)
    if current_user && current_user.user?
      @services = Service.where("user_id = " + current_user.getid.to_s).order(day: :desc)
    end
    @services.each do |service|
      
      if service.driver != nil
        service.driverName = getProfileName(service.driver)
      else
        service.driverName = '(Pending)'
      end
      if service.user_id != nil
        service.userName = getProfileName(service.user_id)
      else
        service.userName = ''
      end
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
  end

  # GET /services/new
  def new
    @service = Service.new
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(service_params)
    @service.user_id = current_user.id
    @service.amount = [10, 15, 25, 35].sample
    
    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Your Service has been successfully received, if you are agree with the cost, please Confirm it.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        if current_user && current_user.user?
          format.html { redirect_to @service, notice: 'Your Service has been successfully updated, if you are agree with the cost, please Confirm it.' }
          format.json { render :show, status: :ok, location: @service }
        else
          format.html { redirect_to services_path, notice: 'The Driver was assigned successfully.' }
          format.json { head :no_content }
        end
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json

  def confirm
    @service.confirm
    respond_to do |format|
      format.html { redirect_to services_path, notice: 'Confirmation number: ' + @service.nroConfirmation  + ', Your service has been registered, We will see you soon.' }
      format.json { head :no_content }
    end
  end

  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_path, notice: 'The Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def favorite
    @service.setFavorite
    respond_to do |format|
      format.html { redirect_to services_path, notice: 'It was added as favorite.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:from, :to, :day, :driver, :tipoVehiculo, :qPassengers, :payMethod, :user_id)
    end
end

taxiweb/app/helpers/services_helper.rb
module ServicesHelper
end

taxiweb/app/views/services/_form.html.erb
<%= simple_form_for(@service) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <% if current_user && current_user.user? %>
      <%= f.input :from %>
      <%= f.input :to %>
      <%= f.input :day %>
      <%= f.input :qPassengers %>
      <%= f.input :tipoVehiculo, collection: ['Sedan','Minivan'], :selected => @service.tipoVehiculo %>
      <%= f.input :payMethod, collection: ['Cash','Credit Card'], :selected => @service.payMethod %>
    <% end %>
    
    <% if current_user && current_user.operator? %>
    <label class="select optional">Select Driver</label>
      <%= f.collection_select(:driver, User.where(role: 2 ), :id, :friendly_name ) %>
    <% end %>
    </BR>
    </BR>
    <p>
      <strong style="font-size: 20px;">Cost:</strong>
      <strong style="font-size: 30px;">S/. <%= @service.amount %></strong>
    </P>
  </div>

  <div class="form-actions">
    <% if current_user && current_user.user? %>
      <%= f.button :submit ,'Estimate Service (S/.)',  :class =>'btn btn-primary'%>
    <% else %>
      <%= f.button :submit ,'Save',  :class =>'btn btn-primary'%>
    <% end %>
  </div>
<% end %>

taxiweb/app/views/services/edit.html.erb
<% if current_user && current_user.user? %>
    <h1 class="text-primary">Editing Service</h1>
<% else %>
    <h1 class="text-primary">Assigning driver</h1>
<% end %>

<%= render 'form' %>
</P>
</P>
<% if current_user && current_user.user? %>
<%= link_to 'Show', @service, style: 'color:#FFFFFF;',:class => 'btn btn-primary' %>
<% end %>
<%= link_to 'Back', services_path, style: 'color:#FFFFFF;',:class => 'btn btn-primary' %>

taxiweb/app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<% if current_user && current_user.user? %>
  <h1 class="text-primary">My Services</h1>
  <% else %>
  <h1 class="text-primary">Services</h1>
<% end %>
</P>
<% if current_user && current_user.user? %>
<%= link_to 'New Service', new_service_path, style: 'color:#FFFFFF;',:class => 'btn btn-primary' %>
<% end %>
</P>
<table class="table table-striped table-bordered table-condensed table-hover">
  <thead>
    <tr>
      <th>Nro</th>
      <th>    </th>
      <th>From</th>
      <th>To</th>
      <th>Day</th>
      
      <th>Driver</th>
      <% if current_user && current_user.operator? %>
      <th>User</th>
      <% end %>
      <th colspan="3"></th>
      <% if current_user && current_user.user? %>
        <th>Favorite</th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @services.each do |service| %>
      <tr>
        <td><%= service.nroConfirmation %></td>
        <% if service.confirmed %>
          <td class="success"></td>
        <% else %>
          <td>?</td>
        <% end %>
        <td><%= service.from %></td>
        <td><%= service.to %></td>
        <td><%= service.dayFormat %></td>
        
        <% if current_user %>
          <% if service.hasDriver %>
            <td><%= service.driverName %></td>
          <% else %>
            <% if current_user.user? %>
              <td>pending</td>
            <% else %>
              <td class="danger"><%= link_to 'Assign Driver', edit_service_path(service) %></td>
            <% end %>
          <% end %>
        <% end %>
        
        <% if current_user && current_user.operator? %>
        <td><%= service.userName %></td>
        <% end %>
        <td><%= link_to 'View', service ,:class => 'btn btn-default btn-xs'  %></td>
          <% if current_user && current_user.user? %>
          <td><%= link_to 'Edit', edit_service_path(service),style: 'color:#FFFFFF;',:class => 'btn btn-info btn-xs'  %></td>
          <% end %>
          <% if current_user && current_user.user? %>
            <td><%= link_to 'Delete', service, method: :delete, data: { confirm: 'Are you sure?' },style: 'color:#FFFFFF;',:class => 'btn btn-danger btn-xs' %></td>
            <% if service.favorite %>
              <td bgcolor="#f0ad4e"><%= link_to 'Remove', favorite_service_path(service) ,style: 'color:#FFFFFF;',:class => 'btn btn-warning btn-xs' %></td>
            <% else %>
              <td><%= link_to 'Add', favorite_service_path(service) ,:class => 'btn btn-default btn-xs' %></td>
            <% end %>
          <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

taxiweb/app/views/services/new.html.erb
<h1 class="text-primary">Estimate service</h1>

<%= render 'form' %>
</P>
<%= link_to 'Back', services_path, style: 'color:#FFFFFF;',:class => 'btn btn-primary' %>

taxiweb/app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origin:</strong>
  <%= @service.from %>
</p>

<p>
  <strong>Destiny:</strong>
  <%= @service.to %>
</p>

<p>
  <strong>Date:</strong>
  <%= @service.day %>
</p>

<p>
  <strong>Passengers:</strong>
  <%= @service.qPassengers %>
</p>

<p>
  <strong>Vehicle:</strong>
  <%= @service.tipoVehiculo %>
</p>

<p>
  <strong>Pay method:</strong>
  <%= @service.payMethod %>
</p>

<p>
  <strong style="font-size: 20px;">Cost:</strong>
  <strong style="font-size: 30px;">S/. <%= @service.amount %></strong>
</P>
</P>
</P>
        <td>
        <% if current_user && current_user.user? %>  
          <%= link_to t('.confirm', :default => 'Agree, I confirm'),
                      confirm_service_path(@service),
                      :class => 'btn btn-success' %>
        <% end %>
        </td>
<%= link_to 'Edit', edit_service_path(@service), style: 'color:#FFFFFF;',:class => 'btn btn-primary' %>
<%= link_to 'Back', services_path, style: 'color:#FFFFFF;',:class => 'btn btn-primary' %>