taxiweb/config/routes.rb
Rails.application.routes.draw do
  get 'pages/historyservicies'

  resources :services
  
  get 'pages/pending_services'
  
  get 'services/:id/confirm', controller: :services, action: :confirm, as: :confirm_service
  get 'services/:id/favorite', controller: :services, action: :favorite, as: :favorite_service
  

  
  get 'pages/my_services/:id' , controller: :pages, action: :my_services, as: :pages_my_service

  get 'pages/estimate_cost'

  get 'pages/e'

  resources :profiles
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'pages#estimate_cost'

  get 'pages/about_us'

  get 'pages/faq'

  get 'pages/tos'

  get 'pages/contact_us'

end

taxiweb/app/views/pages/about_us.html.erb
<h1>About us</h1>
<p>We are a company dedicated to the taxi service online</p>

taxiweb/app/views/pages/contact_us.html.erb
<h1>Contact Us</h1>

<div class="input-group">
  <input type="text" class="form-control" placeholder="Recipient's username" aria-describedby="basic-addon2">
  <span class="input-group-addon" id="basic-addon2">@example.com</span>
</div>
<br />
<div class="input-group">
  <span class="input-group-addon" id="basic-addon1">mail subject</span>
  <input type="text" class="form-control" placeholder="Username" aria-describedby="basic-addon1">
</div>

<br />


<div class="input-group">
  <span class="input-group-addon" id="basic-addon1">email content</span>
  <input type="text" class="form-control" placeholder="Username" aria-describedby="basic-addon1">
</div>
<br />

<div class="btn-group" role="group" aria-label="...">
    <button type="button" class="btn btn-default">Send</button>
</div>
<br />  
<br />

taxiweb/app/views/pages/e.html.erb
<h1>Pages#e</h1>
<p>Find me in app/views/pages/e.html.erb</p>

taxiweb/app/views/pages/faq.html.erb
<h1>Pages#faq</h1>
<p>Find me in app/views/pages/faq.html.erb</p>

taxiweb/app/views/pages/historyservicies.html.erb
<h1 class="text-primary">History Services</h1>

    <% @Services.each do |service| %>
      <div class="jumbotron">
        <h1><%= service.dayFormat %></h1>
        <p>To: <%=  service.to %></p>
        <p>Customer: <%= service.customerName %></p>
        <p><%= link_to "Details", pages_my_service_path(service), class: :"btn btn-primary btn-lg"  %>
          
      </div>
      
<% end %>

taxiweb/app/views/pages/index.html.erb
<h1>The best service of the web</h1>

<div class="jumbotron">
  <h1><img alt="Brand" src="http://www.phoenixshuttle.com/phoenixtaxicabride/images/banner.jpg" /></h1>
  <h1>Welcome to TaxiWeb</h1>
  <p>Welcome to the online service taxiweb</p>
  <p><a class="btn btn-primary btn-lg" href=<%= pages_about_us_path %> role="button">Learn more</a></p>
  <br />
</div>

taxiweb/app/views/pages/my_services.html.erb
<h1>Details Service Nro <%= @Service.id %></h1>

<div class="jumbotron">
  <h1><%= @Service.dayFormat %></h1>
  <p>From: <%= @Service.from %></p>
  <p>To: <%= @Service.to %></p>
  <p>Customer: <%= @Service.customerName %></p>
</div>

<p>
  <%= link_to "Return list", pages_pending_services_path, class: :"btn btn-primary btn-lg" %>
</p>

taxiweb/app/views/pages/pending_services.html.erb
<h1 class="text-primary">Pending Services</h1>
<p></p>

<div class="col-lg-3">
  <div class="well sidebar-nav">
    <ul class="nav nav-list">
    <% @Services.each do |service| %>
      <li>
        <h2><%= service.hourservice %></h2>
        <p><%= link_to "To: " + service.to, pages_my_service_path(service)  %><br />
        <%= service.customerName %><br /></p>
      </li>
    <% end %>
    </ul>
  </div><!--/.well -->
</div><!--/span-->

taxiweb/app/views/pages/tos.html.erb
<h1>Pages#tos</h1>
<p>Find me in app/views/pages/tos.html.erb</p>